name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["1.85.0", stable, beta]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - name: Use Cargo.lock.msrv
        if: matrix.toolchain == '1.85.0'
        run: cp Cargo.lock.msrv Cargo.lock
      - name: Test
        run: make test
